FROM golang:1.21 as builder

WORKDIR /usr/src/app

COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download && go mod verify

COPY ./backend/src ./src

RUN mkdir -p dist

RUN CGO_ENABLED=0 go build -v -o ./dist/ ./...

FROM alpine

COPY --from=builder /usr/src/app/dist/src ./app

CMD ["./app"]