apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: shrtify-de-deployment-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shrtify-de-deployment-postgres
  template:
    metadata:
      labels:
        app: shrtify-de-deployment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secret-shrtify-de-database
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: shrtify-de-persistent-volume-claim