apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shrtify-de-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
