apiVersion: v1
kind: PersistentVolume
metadata:
  name: shrtify-de-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgsql/data"
