#!/bin/bash
set -e

source ../backend/.env

psql -v ON_ERROR_STOP=1 --host $DATABASE_HOST --port $DATABASE_PORT --username "$DATABASE_ADMIN_USERNAME" <<-EOSQL
    DROP USER $DATABASE_USERNAME;
	CREATE USER $DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$DATABASE_PASSWORD';
	CREATE DATABASE $DATABASE_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
	ALTER DATABASE $DATABASE_NAME OWNER TO $DATABASE_USERNAME;
EOSQL